"""Refresh the rent figures used by the MCP server and the web app from a newer RIQ02 file.

    python fetch_rtb.py              # -> rtb_latest.csv (newest quarter per area, from the CSO)
    python update_data.py            # -> mcp_server/rentcheck_data.json (keeps area positions) + web/data/rentcheck-data.js
    python update_data.py --web-only # only re-export the web bundle (data + scam rules) from what's already there

The web app reads web/data/rentcheck-data.js, which is generated here from the same JSON and the same
scam_rules.json the MCP server uses, so the two can't drift apart.
"""
import csv
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "mcp_server" / "rentcheck_data.json"
RULES = HERE / "mcp_server" / "scam_rules.json"
CSV = HERE / "rtb_latest.csv"
WEB = HERE / "web" / "data" / "rentcheck-data.js"
BEDS = {"all bedrooms": "all", "one bed": "1", "two bed": "2", "three bed": "3", "four plus bed": "4"}
TYPES = {"all property types": "all", "apartment": "apt", "other flats": "flat", "detached house": "det",
         "semi detached house": "semi", "terrace house": "terr"}


def refresh_from_csv() -> None:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    rents, latest = {}, 0
    with CSV.open(encoding="utf-8-sig", newline="") as f:
        for r in csv.DictReader(f):
            row = {k.strip().lower(): v for k, v in r.items()}
            b, t = BEDS.get(row["number of bedrooms"].strip().lower()), TYPES.get(row["property type"].strip().lower())
            m = re.search(r"(\d{4})\s*Q\s*([1-4])", row["quarter"])
            if not (b and t and m and row["value"].strip()):
                continue
            q = int(m[1]) * 10 + int(m[2])
            latest = max(latest, q)
            rents.setdefault(row["location"].strip(), {})[f"{b}|{t}"] = [round(float(row["value"])), q]
    for loc in rents:
        rents[loc] = {k: v for k, v in rents[loc].items() if v[1] >= latest - 10}
    data.update(rents=rents, latest=latest)
    DATA.write_text(json.dumps(data, separators=(",", ":")), encoding="utf-8")
    new = [n for n in rents if n not in data["places"]]
    print(f"Updated to {latest // 10} Q{latest % 10}: {len(rents)} areas. {len(new)} have no map position yet.")


def export_web() -> None:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    rules = json.loads(RULES.read_text(encoding="utf-8"))
    rules.pop("_about", None)
    WEB.parent.mkdir(parents=True, exist_ok=True)
    WEB.write_text(
        "// Generated by update_data.py from mcp_server/rentcheck_data.json and mcp_server/scam_rules.json. Do not edit.\n"
        f"window.RENTCHECK_DATA = {json.dumps(data, separators=(',', ':'), ensure_ascii=False)};\n"
        f"window.RENTCHECK_RULES = {json.dumps(rules, separators=(',', ':'), ensure_ascii=False)};\n",
        encoding="utf-8", newline="\n")
    print(f"Wrote {WEB.relative_to(HERE)} ({data['latest'] // 10} Q{data['latest'] % 10}, {len(data['rents'])} areas).")


if __name__ == "__main__":
    if "--web-only" not in sys.argv:
        if CSV.exists():
            refresh_from_csv()
        else:
            print("No rtb_latest.csv found (run fetch_rtb.py first); keeping the current rent snapshot.")
    export_web()
